# -*- coding: utf-8 -*-
"""Capstone3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12V_YvVVrLxo0EgEpjSom9r1KY7rr76UY
"""

from google.colab import drive
drive.mount('/content/drive')

#!pip uninstall openai langchain langchain-openai -y

!pip install openai
!pip install langchain
!pip install langchain-openai
!pip install langchain-community
!pip install langgraph
!pip install --upgrade qdrant-client # Added --upgrade to ensure latest version
!pip install streamlit
!pip install pandas
!pip install tiktoken

from getpass import getpass
import os

os.environ["OPENAI_API_KEY"] = getpass("OpenAI API Key: ")
os.environ["QDRANT_URL"] = getpass("Qdrant URL: ")
os.environ["QDRANT_API_KEY"] = getpass("Qdrant API Key: ")

print("Environment Loaded")

from openai import OpenAI

client = OpenAI()

response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {
            "role": "user",
            "content": "Halo"
        }
    ]
)

print(response.choices[0].message.content)

import os
import uuid
import pandas as pd

from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct

from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings

from langchain.tools import tool

from langgraph.graph import StateGraph

from langchain_community.callbacks.manager import get_openai_callback

embedding_model = OpenAIEmbeddings(
    model="text-embedding-3-large"
)

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

print("LLM Ready")

client_qdrant = QdrantClient(
    url=os.getenv("QDRANT_URL"),
    api_key=os.getenv("QDRANT_API_KEY"),
    timeout=60 # Increased timeout to 60 seconds
)

print("Connected to Qdrant")

file_path = "/content/drive/MyDrive/Data/Resume.csv"

df = pd.read_csv(file_path)

df.head()

df = df.dropna()

texts = df["Resume_str"].tolist()[:100]

len(texts)

client_qdrant.recreate_collection(
    collection_name="resumes",
    vectors_config={
        "size": 3072,
        "distance": "Cosine"
    }
)

print("Collection Created")

if client_qdrant.collection_exists(collection_name="resumes"):
    print("Collection 'resumes' already exists.")
else:
    client_qdrant.create_collection(
        collection_name="resumes",
        vectors_config={
            "size": 3072,
            "distance": "Cosine"
        }
    )
    print("Collection 'resumes' Created")

vectors = embedding_model.embed_documents(texts)

len(vectors)

points = []

for i, vector in enumerate(vectors):

    points.append(
        PointStruct(
            id=str(uuid.uuid4()),
            vector=vector,
            payload={
                "text": texts[i]
            }
        )
    )

client_qdrant.upsert(
    collection_name="resumes",
    points=points
)

print("Vector Inserted")

@tool
def get_relevant_docs(question: str):
    """
    Retrieve relevant resumes from vector database.
    """

    query_vector = embedding_model.embed_query(question)

    results = client_qdrant.query_points(
        collection_name="resumes",
        query=query_vector,
        limit=5
    ).points

    return results

def rewrite_query(query, history):

    prompt = f"""
    You are an expert HR AI Assistant.

    Chat History:
    {history}

    Current User Question:
    {query}

    Rewrite the query into a professional HR search query.
    """

    response = llm.invoke(prompt)

    return response.content

def retrieval_agent(state):

    query = state["query"]
    history = state["history"]

    rewritten_query = rewrite_query(query, history)

    docs = get_relevant_docs.invoke(rewritten_query)

    state["documents"] = docs
    state["rewritten_query"] = rewritten_query

    return state

def analyzer_agent(state):

    docs = state["documents"]

    prompt = f"""
    You are an expert HR Analyst.

    Analyze these candidate resumes carefully.

    Documents:
    {docs}

    Return:
    - Candidate Summary
    - Skills
    - Experience
    - Education
    """

    response = llm.invoke(prompt)

    state["analysis"] = response.content

    return state

def ranking_agent(state):

    analysis = state["analysis"]

    prompt = f"""
    Rank the candidates based on relevance.

    {analysis}

    Return:
    - Candidate Name
    - Match Score
    - Reason
    """

    response = llm.invoke(prompt)

    state["final_answer"] = response.content

    return state

workflow = StateGraph(dict)

workflow.add_node("retrieve", retrieval_agent)
workflow.add_node("analyze", analyzer_agent)
workflow.add_node("rank", ranking_agent)

workflow.set_entry_point("retrieve")

workflow.add_edge("retrieve", "analyze")
workflow.add_edge("analyze", "rank")

graph = workflow.compile()

print("Multi-Agent Workflow Ready")

result = graph.invoke({
    "query": "Find Python Data Scientist",
    "history": ""
})

print(result["final_answer"])

print(df.shape)

client_qdrant.count(
    collection_name="resumes"
)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import os
# 
# from qdrant_client import QdrantClient
# 
# from langchain_openai import ChatOpenAI
# from langchain_openai import OpenAIEmbeddings
# 
# from langchain_community.callbacks.manager import get_openai_callback
# 
# from langchain.tools import tool
# 
# from langgraph.graph import StateGraph
# 
# 
# # =========================
# # PAGE CONFIG
# # =========================
# 
# st.set_page_config(
#     page_title="AI Talent Intelligence System",
#     page_icon="🧠",
#     layout="wide"
# )
# 
# st.title("🧠 AI Talent Intelligence System")
# 
# 
# # =========================
# # SESSION STATE
# # =========================
# 
# if "chat_history" not in st.session_state:
#     st.session_state.chat_history = []
# 
# 
# # =========================
# # OPENAI & QDRANT
# # =========================
# 
# embedding_model = OpenAIEmbeddings(
#     model="text-embedding-3-large"
# )
# 
# llm = ChatOpenAI(
#     model="gpt-4o-mini",
#     temperature=0
# )
# 
# client_qdrant = QdrantClient(
#     url=st.secrets["QDRANT_URL"],
#     api_key=st.secrets["QDRANT_API_KEY"]
# )
# 
# 
# # =========================
# # RAG TOOL
# # =========================
# 
# @tool
# def get_relevant_docs(question: str):
# 
#     query_vector = embedding_model.embed_query(question)
# 
#     results = client_qdrant.search(
#         collection_name="resumes",
#         query_vector=query_vector,
#         limit=5
#     )
# 
#     return results
# 
# 
# # =========================
# # QUERY REWRITE
# # =========================
# 
# def rewrite_query(query, history):
# 
#     prompt = f"""
#     Chat History:
#     {history}
# 
#     User Question:
#     {query}
# 
#     Rewrite into professional HR query.
#     """
# 
#     response = llm.invoke(prompt)
# 
#     return response.content
# 
# 
# # =========================
# # AGENTS
# # =========================
# 
# def retrieval_agent(state):
# 
#     query = state["query"]
#     history = state["history"]
# 
#     rewritten_query = rewrite_query(query, history)
# 
#     docs = get_relevant_docs.invoke(rewritten_query)
# 
#     state["documents"] = docs
#     state["rewritten_query"] = rewritten_query
# 
#     return state
# 
# 
# def analyzer_agent(state):
# 
#     docs = state["documents"]
# 
#     prompt = f"""
#     Analyze these resumes.
# 
#     Documents:
#     {docs}
# 
#     Return:
#     - Candidate Summary
#     - Skills
#     - Experience
#     """
# 
#     response = llm.invoke(prompt)
# 
#     state["analysis"] = response.content
# 
#     return state
# 
# 
# def ranking_agent(state):
# 
#     analysis = state["analysis"]
# 
#     prompt = f"""
#     Rank candidates.
# 
#     {analysis}
#     """
# 
#     response = llm.invoke(prompt)
# 
#     state["final_answer"] = response.content
# 
#     return state
# 
# 
# # =========================
# # LANGGRAPH
# # =========================
# 
# workflow = StateGraph(dict)
# 
# workflow.add_node("retrieve", retrieval_agent)
# workflow.add_node("analyze", analyzer_agent)
# workflow.add_node("rank", ranking_agent)
# 
# workflow.set_entry_point("retrieve")
# 
# workflow.add_edge("retrieve", "analyze")
# workflow.add_edge("analyze", "rank")
# 
# graph = workflow.compile()
# 
# 
# # =========================
# # CHAT UI
# # =========================
# 
# user_input = st.chat_input("Ask something about candidates...")
# 
# if user_input:
# 
#     st.chat_message("user").write(user_input)
# 
#     history_text = "\n".join([
#         f"User: {x['query']}\nAI: {x['answer']}"
#         for x in st.session_state.chat_history[-3:]
#     ])
# 
#     with get_openai_callback() as cb:
# 
#         result = graph.invoke({
#             "query": user_input,
#             "history": history_text
#         })
# 
#     answer = result["final_answer"]
# 
#     st.chat_message("assistant").write(answer)
# 
#     # =========================
#     # SOURCE DOCUMENTS
#     # =========================
# 
#     with st.expander("📄 Source Documents"):
# 
#         for i, doc in enumerate(result["documents"]):
# 
#             st.write(f"### Document {i+1}")
#             st.write(doc.payload["text"][:500])
# 
# 
#     # =========================
#     # TOKEN USAGE
#     # =========================
# 
#     with st.expander("📈 Token Usage"):
# 
#         st.write("Prompt Tokens:", cb.prompt_tokens)
#         st.write("Completion Tokens:", cb.completion_tokens)
#         st.write("Total Tokens:", cb.total_tokens)
# 
# 
#     # =========================
#     # SAVE HISTORY
#     # =========================
# 
#     st.session_state.chat_history.append({
#         "query": user_input,
#         "answer": answer
#     })
# 
# 
# # =========================
# # HISTORY UI
# # =========================
# 
# with st.sidebar:
# 
#     st.header("🕓 Chat History")
# 
#     for chat in reversed(st.session_state.chat_history[-5:]):
# 
#         st.write("User:", chat["query"])
#         st.write("AI:", chat["answer"])
#         st.divider()